name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: composer:latest

    permissions: read-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  


      - name: Ejecutar composer install
        run: composer install

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Ejecutar docker-compose up
        run: docker-compose -f docker-compose.yml up -d
