name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: composer:latest

    permissions: read-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Ejecutar docker-compose up
        run: |
          docker-compose -f docker-compose.yml up -d > docker-compose-output.log 2>&1
          cat docker-compose-output.log
