on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

name: Main Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download and make executable wait-for-it.sh
        run: |
          curl -L https://github.com/vishnubob/wait-for-it/releases/download/v1.11.0/wait-for-it.sh -o wait-for-it.sh
          chmod +x wait-for-it.sh

      - name: Docker Compose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker/docker-compose.yml"

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_SHA: ${{ github.sha }}
        with:
          args: >
            -Dsonar.projectKey=prueba10
            -Dsonar.sources=.
            -Dsonar.qualitygate.wait=true

      - name: Teardown
        run: docker-compose down