name: test project0

on:
  pull_request:
    branches: [master]
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código
        uses: actions/checkout@v2

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Inicializar Terraform
        run: terraform init

      - name: Aplicar Terraform
        run: terraform apply -auto-approve

  test2:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Obtener código
        uses: actions/checkout@v2

