name: test project

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Update Commit Status
        uses: ouzi-dev/commit-status-updater@v2
        with:
          token: ${{ secrets.SECRET}}
          status: success  
          description: Terraform applied successfully